[package]
name = "day_5"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
csv = "1.3.1"
itertools = "0.13.0"
serde = { version = "1.0.215", features = ["derive"] }
