[package]
name = "day_6"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
clap = { version = "4.5.23", features = ["derive"] }
indicatif = { version = "0.17.9", features = ["rayon"] }
itertools = "0.13.0"
rayon = "1.10.0"

[profile.release]
debug = true
